//products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
//cart
export const FETCH_CART_PRODUCTS = "FETCH_CART_PRODUCTS";
export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";
